services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "9000:9000"
  chatbotservice:
    build:
      context: ./service/chatbotservice
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  clawlerservice:
    build:
      context: ./service/clawlerservice
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
